import Link from "next/link";

const services = [
  ["Periodic Service", "Oil, filters, fluids & 40-point inspection", "from ₹1,499"],
  ["AC & Cooling", "Diagnostics, gas refill & climate checks", "from ₹799"],
  ["Brakes & Suspension", "Inspection, repair & replacement", "from ₹999"],
  ["Detailing & Care", "Interior deep clean, polish & protection", "from ₹1,999"],
];

const process = ["Tell us what your car needs", "Get a clear estimate before work", "Track the service progress", "Drive away with confidence"];

export const metadata = {
  title: "TorqueWorks Auto Care — Automobile Demo",
  description: "A conversion-focused car and bike service centre website demo with service booking, estimates and contact CTAs.",
};

export default function AutomobilePage() {
  return (
    <main className="min-h-screen bg-[#101111] text-white">
      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#101111]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="text-xl font-black tracking-[-.06em]">TORQUE<span className="text-[#d5ff3f]">WORKS</span></Link><nav className="hidden gap-7 text-sm font-semibold text-white/65 md:flex"><a href="#services">Services</a><a href="#process">How it works</a><a href="#workshop">Workshop</a></nav><a href="tel:+919876543210" className="rounded-full bg-[#d5ff3f] px-5 py-2.5 text-sm font-black text-black">Book service</a></div></header>

      <section className="overflow-hidden border-b border-white/10"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div className="flex flex-col justify-center"><p className="mb-5 text-xs font-bold uppercase tracking-[.25em] text-[#d5ff3f]">Car & bike care · Raipur</p><h1 className="text-6xl font-black leading-[.86] tracking-[-.07em] sm:text-7xl lg:text-[7.8rem]">Drive in.<br/><span className="text-white/25">Drive out</span><br/>better.</h1><p className="mt-8 max-w-xl text-base leading-7 text-white/50 sm:text-lg">Transparent servicing, skilled technicians and a workshop built around getting you safely back on the road.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#services" className="rounded-full bg-[#d5ff3f] px-6 py-3.5 text-sm font-black text-black">Explore services</a><a href="https://wa.me/919876543210" className="rounded-full border border-white/15 px-6 py-3.5 text-sm font-bold">WhatsApp estimate</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-white/45"><span>✓ Pickup & drop</span><span>✓ Genuine parts</span><span>✓ Digital updates</span></div></div><div className="relative aspect-[4/4.7] overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_65%_30%,#d5ff3f,transparent_18%),linear-gradient(145deg,#33382e,#121313)] p-6 sm:p-8"><div className="absolute right-7 top-7 rounded-full border border-[#d5ff3f]/30 bg-[#d5ff3f]/10 px-4 py-2 text-xs font-bold text-[#d5ff3f]">OPEN TODAY · 9 AM–7 PM</div><div className="flex h-full items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/40">Workshop promise</p><p className="mt-3 max-w-md text-4xl font-black tracking-[-.05em] sm:text-5xl">No mystery charges. No shortcuts.</p></div></div></div></div></section>

      <section id="services" className="bg-[#f3f3ee] text-[#101111]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-black/40">Workshop services</p><h2 className="mt-3 text-4xl font-black tracking-[-.06em] sm:text-5xl">Built around your vehicle.</h2></div><a href="https://wa.me/919876543210" className="text-sm font-bold underline underline-offset-4">Get a service estimate →</a></div><div className="mt-12 grid gap-4 sm:grid-cols-2">{services.map(([name, desc, price], i) => <article key={name} className="group rounded-[1.75rem] border border-black/10 bg-white p-6 transition hover:-translate-y-1"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#101111] text-sm font-black text-[#d5ff3f]">0{i + 1}</span><span className="rounded-full bg-[#d5ff3f] px-3 py-1 text-xs font-black">{price}</span></div><h3 className="mt-14 text-2xl font-black tracking-tight">{name}</h3><p className="mt-2 max-w-md text-sm leading-6 text-black/50">{desc}</p><a href="tel:+919876543210" className="mt-7 inline-block text-sm font-bold">Book this service →</a></article>)}</div></div></section>

      <section id="process" className="border-y border-white/10"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d5ff3f]">Simple service process</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-[-.06em] sm:text-5xl">Know what&apos;s happening at every step.</h2><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{process.map((item, i) => <div key={item} className="rounded-3xl border border-white/10 p-6"><span className="text-sm font-black text-[#d5ff3f]">0{i + 1}</span><p className="mt-12 text-lg font-bold leading-6">{item}</p></div>)}</div></div></section>

      <section id="workshop" className="bg-[#d5ff3f] text-[#101111]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1fr_.9fr] lg:px-8 lg:py-24"><div><p className="text-xs font-black uppercase tracking-[.2em] text-black/45">TorqueWorks workshop</p><h2 className="mt-3 text-5xl font-black leading-[.9] tracking-[-.07em] sm:text-6xl">Your car.<br/>Our checklist.</h2><p className="mt-6 max-w-xl leading-7 text-black/60">Modern diagnostics, trained technicians and a clean, organised workshop in the heart of Raipur.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://maps.google.com/?q=Raipur+Chhattisgarh" className="rounded-full bg-[#101111] px-6 py-3.5 text-sm font-black text-white">Get directions</a><a href="tel:+919876543210" className="rounded-full border border-black/20 px-6 py-3.5 text-sm font-black">Call workshop</a></div></div><div className="min-h-[320px] rounded-[2rem] bg-[radial-gradient(circle_at_60%_35%,#ffffff,transparent_20%),linear-gradient(135deg,#6b7548,#20241e)] p-6"><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-black">Raipur · CG</span></div></div></section>

      <section className="bg-[#f3f3ee] px-5 py-20 text-[#101111] lg:px-8 lg:py-28"><div className="mx-auto max-w-4xl rounded-[2rem] bg-[#101111] px-7 py-14 text-center text-white sm:px-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d5ff3f]">Ready for service?</p><h2 className="mt-4 text-4xl font-black tracking-[-.06em] sm:text-6xl">Tell us what your vehicle needs.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-white/50">Send your vehicle model and the issue. We&apos;ll help you choose the right service and estimate.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="https://wa.me/919876543210" className="rounded-full bg-[#d5ff3f] px-7 py-3.5 text-sm font-black text-black">WhatsApp us</a><a href="tel:+919876543210" className="rounded-full border border-white/15 px-7 py-3.5 text-sm font-bold">Call now</a></div></div></section>

      <footer className="border-t border-white/10 px-5 py-8 text-center text-xs text-white/35">TorqueWorks Auto Care · Automobile Demo · <Link href="/" className="underline underline-offset-4">Back to all demos</Link></footer>
    </main>
  );
}
