import Link from "next/link";

const properties = [
  ["The Aria Residences", "3 & 4 BHK · New launch", "₹1.42 Cr", "From 1,850 sq ft"],
  ["Palm Grove Villas", "4 BHK · Gated community", "₹2.35 Cr", "From 2,700 sq ft"],
  ["Skyline One", "2 & 3 BHK · City living", "₹89 Lakh", "From 1,180 sq ft"],
];

const services = ["Residential sales", "Property investment", "Site visits", "Home loan assistance", "Resale & rentals", "Legal & documentation"];

export const metadata = {
  title: "Aarohan Properties — Real Estate Demo",
  description: "A premium real estate website demo focused on property discovery, site visits and buyer enquiries.",
};

export default function RealEstatePage() {
  return (
    <main className="min-h-screen bg-[#f4f0e8] text-[#191815]">
      <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f4f0e8]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="font-serif text-2xl tracking-tight">Aarohan <span className="text-[#8a6740]">Properties</span></Link><nav className="hidden gap-7 text-sm font-medium md:flex"><a href="#properties">Properties</a><a href="#services">Services</a><a href="#about">About us</a></nav><a href="#contact" className="rounded-full bg-[#191815] px-5 py-2.5 text-sm font-semibold text-white">Find my property</a></div></header>

      <section className="bg-[#25271f] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div className="flex flex-col justify-center"><p className="mb-5 text-xs font-bold uppercase tracking-[.25em] text-[#d8bb8e]">Residential real estate · Raipur</p><h1 className="font-serif text-6xl leading-[.9] tracking-[-.045em] sm:text-7xl lg:text-[7.6rem]">Find a place<br/><i>to belong.</i></h1><p className="mt-8 max-w-xl text-base leading-7 text-white/55 sm:text-lg">Curated homes, honest guidance and a property search built around how you actually want to live.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#properties" className="rounded-full bg-[#d8bb8e] px-6 py-3.5 text-sm font-bold text-[#191815]">Explore properties</a><a href="https://wa.me/919876543210" className="rounded-full border border-white/15 px-6 py-3.5 text-sm font-bold">WhatsApp an advisor</a></div></div><div className="relative min-h-[500px] overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_65%_28%,#d8bb8e,transparent_20%),linear-gradient(145deg,#69715f,#20231d)] p-7"><div className="absolute inset-x-7 bottom-7 rounded-3xl border border-white/15 bg-black/20 p-6 backdrop-blur-md"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bb8e]">Featured residence</p><p className="mt-2 font-serif text-3xl">The Aria Residences</p><p className="mt-2 text-sm text-white/50">3 & 4 BHK · Prime city location</p></div></div></div></section>

      <section id="properties" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8a6740]">Featured properties</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Homes worth seeing.</h2></div><a href="https://wa.me/919876543210" className="text-sm font-bold underline underline-offset-4">Ask for all listings →</a></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{properties.map(([name, type, price, size], i) => <article key={name} className="group"><div className={`aspect-[4/4.5] overflow-hidden rounded-[1.75rem] p-5 ${i === 0 ? "bg-gradient-to-br from-[#b7ad94] to-[#59604e]" : i === 1 ? "bg-gradient-to-br from-[#d6c4a2] to-[#765d48]" : "bg-gradient-to-br from-[#9ca89b] to-[#424b43]"}`}><div className="flex h-full flex-col justify-between"><span className="w-fit rounded-full bg-white/75 px-3 py-1 text-xs font-bold text-black">{type}</span><div className="rounded-2xl bg-black/20 p-5 text-white backdrop-blur-sm"><p className="text-sm text-white/60">Starting at</p><p className="mt-1 text-2xl font-black">{price}</p></div></div></div><div className="flex items-end justify-between pt-5"><div><h3 className="font-serif text-2xl">{name}</h3><p className="mt-1 text-sm text-black/45">{size}</p></div><a href="https://wa.me/919876543210" className="text-sm font-bold underline underline-offset-4">Enquire →</a></div></article>)}</div></section>

      <section id="services" className="border-y border-black/10 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8a6740]">How we help</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">More than a property listing.</h2><p className="mt-5 leading-7 text-black/55">From your first shortlist to paperwork and handover, our advisors stay involved.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{services.map((service, i) => <div key={service} className="rounded-2xl border border-black/10 p-5"><span className="text-xs font-bold text-[#8a6740]">0{i + 1}</span><p className="mt-10 font-semibold leading-5">{service}</p></div>)}</div></div></div></section>

      <section id="about" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-10 lg:grid-cols-2"><div className="rounded-[2rem] bg-[#d9ccb6] p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-black/45">Our approach</p><h2 className="mt-20 max-w-lg font-serif text-5xl leading-[.92] sm:text-6xl">Less pressure.<br/><i>Better decisions.</i></h2></div><div className="flex flex-col justify-center"><p className="text-lg leading-8 text-black/65">We believe buying a home should feel informed, not rushed. We listen first, shortlist honestly and make every site visit useful.</p><div className="mt-9 grid grid-cols-3 gap-3 border-t border-black/10 pt-7"><div><strong className="text-2xl">12+</strong><p className="mt-1 text-xs text-black/45">years locally</p></div><div><strong className="text-2xl">450+</strong><p className="mt-1 text-xs text-black/45">families helped</p></div><div><strong className="text-2xl">4.9/5</strong><p className="mt-1 text-xs text-black/45">client rating</p></div></div></div></div></section>

      <section id="contact" className="px-5 pb-20 lg:px-8 lg:pb-28"><div className="mx-auto max-w-4xl rounded-[2rem] bg-[#191815] px-7 py-14 text-center text-white sm:px-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8bb8e]">Start your search</p><h2 className="mt-4 font-serif text-4xl sm:text-6xl">Tell us what you&apos;re looking for.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-white/50">Budget, location, bedrooms — send us the basics and we&apos;ll suggest a shortlist.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="https://wa.me/919876543210" className="rounded-full bg-[#d8bb8e] px-7 py-3.5 text-sm font-bold text-[#191815]">WhatsApp an advisor</a><a href="tel:+919876543210" className="rounded-full border border-white/15 px-7 py-3.5 text-sm font-bold">Call now</a></div></div></section>

      <footer className="border-t border-black/10 px-5 py-8 text-center text-xs text-black/45">Aarohan Properties · Real Estate Demo · <Link href="/" className="underline underline-offset-4">Back to all demos</Link></footer>
    </main>
  );
}
