import { ArrowRight, CalendarDays, CheckCircle2, Clock3, MapPin, MessageCircle, Phone, ShieldCheck, Stethoscope } from "lucide-react";

const services = [
  ["General Consultation", "Everyday health concerns, preventive care and ongoing guidance."],
  ["Diagnostics & Screening", "Clear screening pathways with patient-friendly explanations."],
  ["Specialist Care", "Focused consultations with a professional, structured experience."],
  ["Preventive Health", "Routine check-ups and practical wellness guidance for families."],
];

export const metadata = {
  title: "Clinic & Doctor Website Demo | Local Business Demo Studio",
  description: "A professional healthcare website demo focused on trust, appointments, services and patient enquiries.",
};

export default function ClinicPage() {
  return (
    <main className="bg-[#f7faf9] text-[#12201d]">
      <nav className="sticky top-0 z-30 border-b border-[#12201d]/10 bg-[#f7faf9]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
          <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-[#123d35] text-white"><Stethoscope size={19} /></div><div><p className="text-sm font-black tracking-tight">Aarogya Care</p><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#12201d]/45">Clinic & Diagnostics</p></div></div>
          <div className="hidden items-center gap-7 text-sm font-semibold text-[#12201d]/65 md:flex"><a href="#services">Services</a><a href="#doctor">Doctor</a><a href="#appointment">Appointment</a><a href="#location">Location</a></div>
          <a href="#appointment" className="inline-flex items-center gap-2 rounded-full bg-[#123d35] px-4 py-2.5 text-xs font-bold text-white">Book appointment <ArrowRight size={14} /></a>
        </div>
      </nav>

      <section className="overflow-hidden border-b border-[#12201d]/10">
        <div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-24">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-[#123d35]/15 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-[#123d35]"><ShieldCheck size={14} /> Care you can trust</div>
            <h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.94] tracking-[-0.065em] sm:text-7xl">Healthcare that feels clear, calm and close to home.</h1>
            <p className="mt-6 max-w-xl text-base leading-7 text-[#12201d]/58">A professional clinic website concept designed to help patients understand your services, meet their doctor and take the next step without confusion.</p>
            <div className="mt-8 flex flex-wrap gap-3"><a href="#appointment" className="inline-flex items-center gap-2 rounded-full bg-[#123d35] px-6 py-3.5 text-sm font-bold text-white">Request an appointment <CalendarDays size={17} /></a><a href="https://wa.me/919999999999" className="inline-flex items-center gap-2 rounded-full border border-[#12201d]/15 bg-white px-6 py-3.5 text-sm font-bold"><MessageCircle size={17} /> WhatsApp</a></div>
            <div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-[#12201d]/55"><span className="inline-flex items-center gap-2"><CheckCircle2 size={16} /> Patient-first care</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={16} /> Easy appointments</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={16} /> Clear information</span></div>
          </div>
          <div className="rounded-[2rem] bg-[#dfeee9] p-5 sm:p-7"><div className="rounded-[1.5rem] bg-white p-7 shadow-[0_25px_80px_rgba(18,61,53,.12)]"><div className="flex items-center justify-between"><span className="rounded-full bg-[#e8f4f0] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.15em] text-[#123d35]">Today</span><span className="text-xs font-bold text-[#12201d]/35">Appointments</span></div><div className="mt-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#12201d]/35">Next available</p><p className="mt-2 text-4xl font-black tracking-[-0.05em]">10:30 AM</p><p className="mt-2 text-sm text-[#12201d]/50">General consultation · Dr. Meera Sharma</p></div><div className="mt-8 grid grid-cols-3 gap-2">{["10:30", "11:15", "12:00"].map((time, i) => <div key={time} className={`rounded-xl p-3 text-center text-xs font-bold ${i === 0 ? "bg-[#123d35] text-white" : "bg-[#f1f5f3] text-[#12201d]/55"}`}>{time}</div>)}</div><a href="#appointment" className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-[#123d35] px-4 py-3.5 text-sm font-bold text-white">Choose an appointment <ArrowRight size={15} /></a></div></div>
        </div>
      </section>

      <section id="doctor" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24">
        <div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div className="aspect-[4/5] rounded-[2rem] bg-gradient-to-br from-[#b8d5cc] via-[#dcebe6] to-[#91b8ac] p-6"><div className="flex h-full items-end rounded-[1.5rem] border border-white/60 p-6"><div className="rounded-2xl bg-white/90 p-5 backdrop-blur"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#123d35]/55">Lead physician</p><h2 className="mt-2 text-2xl font-black">Dr. Meera Sharma</h2><p className="mt-1 text-sm font-semibold text-[#123d35]">MBBS · Family Medicine</p></div></div></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#123d35]/55">Meet your doctor</p><h2 className="mt-3 text-4xl font-black tracking-[-0.055em] sm:text-5xl">Professional expertise, explained in a human way.</h2><p className="mt-5 max-w-xl leading-7 text-[#12201d]/55">Patients should be able to understand who is treating them, what they specialise in and why they can trust the practice before making an appointment.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#12201d]/10 bg-white p-5"><p className="text-2xl font-black">12+</p><p className="mt-1 text-sm text-[#12201d]/50">Years of experience</p></div><div className="rounded-2xl border border-[#12201d]/10 bg-white p-5"><p className="text-2xl font-black">4.9/5</p><p className="mt-1 text-sm text-[#12201d]/50">Patient rating</p></div></div></div></div>
      </section>

      <section id="services" className="bg-white border-y border-[#12201d]/10"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#123d35]/55">Services</p><h2 className="mt-3 text-4xl font-black tracking-[-0.055em] sm:text-5xl">Help patients find the right care.</h2></div><div className="mt-10 grid gap-3 md:grid-cols-2">{services.map(([title, detail], index) => <article key={title} className="group rounded-[1.75rem] border border-[#12201d]/10 p-6 transition duration-300 hover:-translate-y-1 hover:border-[#123d35]/30 hover:shadow-[0_20px_60px_rgba(18,61,53,.08)]"><div className="flex size-11 items-center justify-center rounded-xl bg-[#e8f4f0] text-sm font-black text-[#123d35]">0{index + 1}</div><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-[#12201d]/50">{detail}</p><a href="#appointment" className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-[#123d35]">Learn more <ArrowRight size={15} /></a></article>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[2rem] bg-[#123d35] p-8 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/45">Why patients choose us</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-0.055em] sm:text-5xl">Trust should be visible before the first visit.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2">{["Transparent information", "Qualified medical team", "Easy appointment requests", "Convenient location & timings"].map((item) => <div key={item} className="rounded-2xl border border-white/10 p-4 text-sm font-semibold text-white/80"><CheckCircle2 className="mb-7" size={17} />{item}</div>)}</div></div><div className="rounded-[2rem] bg-[#eef5f2] p-8 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#123d35]/50">Patient feedback</p><p className="mt-10 text-2xl font-bold leading-9">“The information was clear, the doctor profile felt trustworthy, and booking took less than a minute.”</p><p className="mt-6 text-sm font-semibold text-[#12201d]/45">— Demo patient review</p></div></div></section>

      <section id="location" className="bg-[#e8f2ef]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-8 lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#123d35]/55">Visit the clinic</p><h2 className="mt-3 text-4xl font-black tracking-[-0.055em]">Easy to find. Easy to contact.</h2><div className="mt-8 space-y-4 text-sm text-[#12201d]/60"><p className="flex gap-3"><MapPin className="shrink-0 text-[#123d35]" size={19} /> 24 Green Avenue, Central City</p><p className="flex gap-3"><Clock3 className="shrink-0 text-[#123d35]" size={19} /> Mon–Sat · 9:00 AM – 7:00 PM</p><p className="flex gap-3"><Phone className="shrink-0 text-[#123d35]" size={19} /> +91 99999 99999</p></div></div><div className="flex min-h-64 items-center justify-center rounded-[2rem] border border-[#123d35]/10 bg-white p-8 text-center"><div><MapPin className="mx-auto text-[#123d35]" size={30} /><p className="mt-4 font-bold">Google Maps integration</p><p className="mt-2 text-sm text-[#12201d]/45">The final client website can embed the real clinic location and directions.</p></div></div></div></section>

      <section id="appointment" className="bg-[#12201d] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#8ed0be]">Book a consultation</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-0.055em] sm:text-6xl">Make the next step simple for every patient.</h2><p className="mt-5 max-w-2xl leading-7 text-white/50">This demo can be customised with the clinic's real doctors, services, timings, location, branding and appointment workflow.</p></div><div className="flex flex-wrap gap-3"><a href="https://wa.me/919999999999" className="inline-flex items-center gap-2 rounded-full bg-[#8ed0be] px-6 py-3.5 text-sm font-bold text-[#12201d]"><MessageCircle size={17} /> WhatsApp</a><a href="tel:+919999999999" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 text-sm font-bold"><Phone size={17} /> Call now</a></div></div></section>

      <div className="fixed inset-x-3 bottom-3 z-40 flex gap-2 rounded-2xl border border-white/20 bg-[#12201d]/95 p-2 shadow-2xl backdrop-blur md:hidden"><a href="https://wa.me/919999999999" className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#8ed0be] py-3 text-sm font-bold text-[#12201d]"><MessageCircle size={16} /> WhatsApp</a><a href="tel:+919999999999" className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-white/15 py-3 text-sm font-bold text-white"><Phone size={16} /> Call</a></div>
    </main>
  );
}
