import Link from "next/link";

const products = [
  ["Everyday Essentials", "Home, kitchen & lifestyle", "120+ items"],
  ["Fresh Arrivals", "New finds for the season", "Updated weekly"],
  ["Best Sellers", "What your neighbourhood loves", "Top picks"],
  ["Special Offers", "Local deals & bundle savings", "This week"],
];

const categories = ["Home & Kitchen", "Fashion & Accessories", "Electronics", "Grocery & Daily Needs", "Beauty & Personal Care", "Gifts & Lifestyle"];

export const metadata = { title: "Nook & Co. — Local Store Demo", description: "A premium local retail website demo focused on products, offers, store discovery and enquiries." };

export default function RetailPage() {
  return (
    <main className="min-h-screen bg-[#f6f6f2] text-[#161714]">
      <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f6f6f2]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="text-xl font-black tracking-[-.05em]">NOOK & CO.</Link><nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#categories">Categories</a><a href="#featured">Featured</a><a href="#store">Our store</a></nav><a href="#store" className="rounded-full bg-[#161714] px-5 py-2.5 text-sm font-semibold text-white">Visit store</a></div></header>

      <section className="mx-auto max-w-7xl px-5 pb-20 pt-16 lg:px-8 lg:pb-28 lg:pt-24"><div className="grid items-end gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.24em] text-black/45">Your neighbourhood store · Bhopal</p><h1 className="max-w-4xl text-6xl font-black leading-[.88] tracking-[-.07em] sm:text-7xl lg:text-[7.8rem]">Good finds.<br/><span className="text-black/30">Close to home.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-black/55 sm:text-lg">A modern local store for everyday essentials, thoughtful finds and the little things you didn&apos;t know you needed.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#featured" className="rounded-full bg-[#161714] px-6 py-3.5 text-sm font-bold text-white">Shop the highlights</a><a href="#store" className="rounded-full border border-black/15 px-6 py-3.5 text-sm font-bold">Get directions</a></div></div><div className="rounded-[2rem] bg-[#d7d8ca] p-6 sm:p-8"><div className="aspect-square rounded-[1.5rem] bg-[radial-gradient(circle_at_30%_25%,#f0eee3,transparent_20%),linear-gradient(135deg,#8c957c,#d6c4a1)] p-6"><div className="flex h-full flex-col justify-between"><span className="w-fit rounded-full bg-white/75 px-3 py-1 text-xs font-bold">Store pick · #01</span><div><p className="max-w-sm text-4xl font-black tracking-[-.05em] sm:text-5xl">Things that make everyday better.</p><p className="mt-4 max-w-xs text-sm leading-6 text-black/55">Curated products from brands we actually like.</p></div></div></div></div></div></section>

      <section id="categories" className="border-y border-black/10 bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><p className="text-xs font-bold uppercase tracking-[.2em] text-black/40">Browse by category</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-[-.05em] sm:text-5xl">A little bit of everything.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((item, i) => <a href="#featured" key={item} className="group flex min-h-32 items-end justify-between rounded-3xl border border-black/10 p-6 transition hover:-translate-y-1 hover:bg-[#f6f6f2]"><span className="max-w-[170px] text-lg font-bold tracking-tight">{item}</span><span className="text-black/35 transition group-hover:translate-x-1">0{i + 1} →</span></a>)}</div></div></section>

      <section id="featured" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-black/40">Shop highlights</p><h2 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Picked for your week.</h2></div><a href="https://wa.me/919876543210" className="text-sm font-bold underline underline-offset-4">Ask about availability →</a></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.map(([name, desc, count], i) => <article key={name}><div className={`aspect-[4/5] rounded-[1.5rem] ${i === 0 ? "bg-gradient-to-br from-[#d8d6c9] to-[#7e8872]" : i === 1 ? "bg-gradient-to-br from-[#e2d1b8] to-[#a86e52]" : i === 2 ? "bg-gradient-to-br from-[#c5c9bb] to-[#59675d]" : "bg-gradient-to-br from-[#e4c5a9] to-[#866246]"} p-5`}><span className="rounded-full bg-white/75 px-3 py-1 text-xs font-bold">{count}</span></div><h3 className="mt-5 text-xl font-black tracking-tight">{name}</h3><p className="mt-2 text-sm leading-6 text-black/50">{desc}</p><a href="https://wa.me/919876543210" className="mt-4 inline-block text-sm font-bold underline underline-offset-4">Ask on WhatsApp →</a></article>)}</div></section>

      <section id="store" className="border-y border-black/10 bg-[#171714] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-white/40">Visit us</p><h2 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-6xl">Come in. Take your time.</h2><p className="mt-6 max-w-xl leading-7 text-white/55">12 Market Street, Arera Colony, Bhopal · Open daily, 9:30 AM–9:00 PM.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://maps.google.com/?q=Bhopal+Madhya+Pradesh" className="rounded-full bg-white px-6 py-3.5 text-sm font-bold text-black">Get directions</a><a href="tel:+919876543210" className="rounded-full border border-white/20 px-6 py-3.5 text-sm font-bold">Call store</a></div></div><div className="min-h-[300px] rounded-[1.75rem] bg-[radial-gradient(circle_at_55%_40%,#a5ad8d,transparent_24%),linear-gradient(135deg,#3f473e,#7b735e)] p-6"><span className="rounded-full bg-white/80 px-3 py-1 text-xs font-bold text-black">Bhopal · MP</span></div></div></section>

      <section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-4xl rounded-[2rem] bg-[#d7d8ca] px-7 py-14 text-center sm:px-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-black/40">Need something specific?</p><h2 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-6xl">Message us before you visit.</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-black/55">Send the product, category or photo you&apos;re looking for and our team can help check availability.</p><a href="https://wa.me/919876543210" className="mt-8 inline-flex rounded-full bg-[#161714] px-7 py-3.5 text-sm font-bold text-white">Chat on WhatsApp</a></div></section>

      <footer className="border-t border-black/10 px-5 py-8 text-center text-xs text-black/45">Nook & Co. · Local Retail Demo · <Link href="/" className="underline underline-offset-4">Back to all demos</Link></footer>
    </main>
  );
}
